# Generated by Django 4.1.7 on 2023-03-03 07:53

from django.conf import settings
from django.db import migrations


def create_site(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    SiteSettings.objects.all().delete()
    SiteSettings.objects.create(
        pk=settings.SITE_ID,
        domain="vms.ndrrma.gov.np",
        name="NDRRMA VMS",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_site)
    ]
