[tool.poetry]
name = "volunteer-management-system"
version = "0.1.0"
description = ""
authors = ["AyushAryal <ayusharyal100@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0"
djangorestframework = "^3.14.0"
django-ckeditor = "^6.7.0"
django-leaflet = "^0.29.0"
django-geojson = "^4.0.0"
psycopg2 = "^2.9.9"


[tool.poetry.group.dev.dependencies]
django-stubs = "^4.2.7"
flake8 = "^7.0.0"
black = "^23.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.django-stubs]
django_settings_module = "volunteer_management_system.settings"

[tool.black]
exclude = "migrations|node_modules"