# Generated by Django 5.0.1 on 2024-01-13 06:06

import ckeditor.fields
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='description')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='point')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.municipality', verbose_name='municipality')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incident')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='volunteer', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('profile_image', models.ImageField(blank=True, upload_to='uploads/images/profile_images/', verbose_name='profile image')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('gender', models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=0, verbose_name='gender')),
                ('blood_group', models.SmallIntegerField(choices=[(0, 'O Negative'), (1, 'O Positive'), (2, 'A Negative'), (3, 'A Positive'), (4, 'B Positive'), (5, 'B Negative'), (6, 'AB Negative'), (7, 'AB Positive')], default=4, verbose_name='blood type')),
                ('nationality', models.SmallIntegerField(choices=[(0, 'National'), (1, 'International')], verbose_name='nationality')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.municipality', verbose_name='municipality')),
            ],
            options={
                'verbose_name': 'Volunteer profile',
                'verbose_name_plural': 'Volunteer profiles',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('vacancy', models.PositiveIntegerField(verbose_name='vacancy')),
                ('description', ckeditor.fields.RichTextField(verbose_name='description')),
                ('status', models.SmallIntegerField(choices=[(0, 'Completed'), (1, 'In Progress'), (2, 'Not Assigned')], verbose_name='status')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.program')),
                ('volunteers', models.ManyToManyField(blank=True, related_name='jobs', to='incident.volunteerprofile', verbose_name='Volunteers Employed')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
