# Generated by Django 5.0.1 on 2024-01-06 05:43

import ckeditor.fields
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=10)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', ckeditor.fields.RichTextField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incident')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('vacancy', models.PositiveIntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('C', 'Completed'), ('P', 'In Progress'), ('U', 'Not Assigned')], max_length=1)),
                ('volunteers', models.ManyToManyField(blank=True, related_name='jobs', to='incident.profile', verbose_name='Volunteers Employed')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.programme')),
            ],
        ),
    ]
