# Generated by Django 5.0.2 on 2024-05-01 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incident",
            options={
                "ordering": ("-date",),
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
            },
        ),
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ("-start_date",),
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
        migrations.AlterModelOptions(
            name="program",
            options={
                "ordering": ("-pk",),
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
            },
        ),
        migrations.AlterModelOptions(
            name="volunteerprofile",
            options={
                "ordering": ("-pk",),
                "verbose_name": "Volunteer profile",
                "verbose_name_plural": "Volunteer profiles",
            },
        ),
    ]
