# Generated by Django 5.0.2 on 2024-05-01 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("federal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="district",
            options={
                "ordering": ("pk",),
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
            },
        ),
        migrations.AlterModelOptions(
            name="municipality",
            options={
                "ordering": ("pk",),
                "verbose_name": "Municipality",
                "verbose_name_plural": "Municipalities",
            },
        ),
        migrations.AlterModelOptions(
            name="province",
            options={
                "ordering": ("pk",),
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
            },
        ),
        migrations.AlterModelOptions(
            name="ward",
            options={
                "ordering": ("pk",),
                "verbose_name": "Ward",
                "verbose_name_plural": "Wards",
            },
        ),
    ]
