# Generated by Django 5.0.1 on 2024-01-06 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.municipality')),
            ],
        ),
    ]
