# Generated by Django 5.0.1 on 2024-01-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_district_province_municipality_district_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
